language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gulp-of-drano' ]; then cd .. && eval "mv $currentfolder generator-gulp-of-drano" && cd generator-gulp-of-drano; fi

